apiVersion: v1
kind: Service
metadata:
  name: aws-new
  namespace: namespace-workflow-1686853237342
spec:
  type: LoadBalancer
  selector:
    app: aws-new
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80